### ISSUE TITLE
how to implementation this on ios ?

### ISSUE THREAD

**Issue by liufsd** [machrisaa/tensorzoom#1]
I'm very interesting this ~

**Comment by machrisaa** [comment]
Hi @liufsd, sorry this is not in the scope of this project and I am not expert in iOS development. You may check the [offical iOS example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples) to get some idea about how to work on iOS. 

While from the point of view on the Android development, the key part is to learn how to modify the [offical Android example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) to add the c++ codes to read your network. Then modify it to build with Bazel to get the .so file. Then move the .so files to the Android project and create the native interface to call the functions in native code that using the Tensorflow.
